# Generated by Django 5.0 on 2025-11-16 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('genre', models.CharField(choices=[('Feline-thriller', 'Feline-thriller'), ('Cat-edy', 'Cat-edy'), ('Purr-drama', 'Purr-drama'), ('Whisker-sci-fi', 'Whisker-sci-fi'), ('Paw-western', 'Paw-western'), ('Meow-horror', 'Meow-horror'), ('Kitten-romance', 'Kitten-romance'), ('Tiger-action', 'Tiger-action')], max_length=50)),
                ('category', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('documentary', 'Documentary')], default='movie', max_length=20)),
                ('poster_url', models.URLField(help_text='Valid HTTPS or HTTP URL to poster image', validators=[django.core.validators.URLValidator()])),
                ('video_url', models.URLField(help_text='Valid HTTPS or HTTP URL to video', validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['genre'], name='movies_movi_genre_f96e97_idx'), models.Index(fields=['year'], name='movies_movi_year_82d175_idx'), models.Index(fields=['title'], name='movies_movi_title_652549_idx')],
            },
        ),
    ]
