# Generated by Django 5.0 on 2025-11-21 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Wide banner image for hero section', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Comma-separated list of actors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='Unknown', help_text="e.g., '1h 45m' or '2 Seasons'", max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Rating from 0.0 to 10.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
